spring:
  datasource:
    url: jdbc:h2:mem:oauth2_local;MODE=MYSQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  sql:
    init:
      mode: never
  web:
    cors:
      allowed-origins: http://localhost:3000

logging:
  level:
    com.eomyoosang.oauth2: DEBUG

security:
  password:
    bcrypt-strength: 10
    policy:
      minimum-length: 10
      require-uppercase: true
      require-lowercase: true
      require-digit: true
      require-special: true
      special-characters: "!@#$%^&*()_+-=[]{}|;:'\",.<>/?"
    compromised:
      enabled: false

auth:
  email-verification:
    ttl-seconds: 900
