spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: oauth2_local
    password: oauth2_local
  data:
    redis:
      host: localhost
      port: 6379
      password:
  jpa:
    hibernate:
      ddl-auto: update
  web:
    cors:
      allowed-origins: http://localhost:3000

logging:
  level:
    com.eomyoosang.oauth2: DEBUG

security:
  password:
    bcrypt-strength: 10
